name: Build and Upload

on:
  push:
    paths-ignore: 
      - 'README.md'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        configuration: [Release]
        include:
          - os: windows-latest
            COMMAND: "AM2R ModPacker.sln" -c Release -r win-x86 -o builds/win
            ARTIFACT: builds/win
    runs-on: ${{ matrix.os }}
    

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore "AM2R ModPacker.sln"
    - name: Build
      run: dotnet publish ${{ matrix.COMMAND }} -c "${{ matrix.configuration }}"
    # Steps for uploading artifacts.
    - name: Zip to Archive
      run: 7z a -tzip ${{ matrix.os }}.zip ./${{ matrix.ARTIFACT }}
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ${{ matrix.os }}
        path: ${{ matrix.os }}.zip
